### ISSUE TITLE
constrain=FALSE bug

### ISSUE THREAD

**Issue by harrysouthworth** [mikesweeting/bcrm#2]
I've spent all day hunting this down and have failed.

If you run the below a few times, you'll see that there is a systematic change at the 100th simulated trial. It's something to do with
if(simulate){
     sub.start <- 100 * floor((sim - 1) / 100)

If you change 100 to 50 (say) and rerun the below, you'll see that the change is introduced at iteration 50.

I don't really get why you stuff things into subset.results and then bind it with results every 100 iterations. Is to try to speed things up by not growing lists? Wouldn't
results <- vector(mode="list", length=nsim)
do a better job?

I'm using the CRAN version of the package but the issue is still there in your Github version.

Anyway, I'll continue to work on it, but if you get to the solution before me, or if you have some clues as to what it might be, I'd be grateful if you were to let me know.

Thanks,
Harry

dose <- 1:12
p.tox0 <- seq(.04, .5, length.out = length(dose))
target.tox <- 0.33
sdose <- log(dose/25)
mu <- c(2.15,0.52)
Sigma <- rbind(c(0.84^2,0.134),c(0.134,0.80^2))

m <- bcrm::bcrm(stop=list(nmax=18), sdose=sdose, dose=dose,
                ff="logit2", prior.alpha=list(4,mu,Sigma),
                target.tox=target.tox, constrain=FALSE,
                pointest=0.25, method="rjags", truep=p.tox0 * 1.5,
                simulate=TRUE, nsim=200)

sapply(m, function(X){
  max(diff(X$data$dose))
}) %>% as.data.frame() %>% 
  mutate(index=1:200) %>% 
  ggplot(aes(index, .)) +
  geom_point(position=position_jitter(height=.1, width=0)) +
  geom_smooth()

**Comment by harrysouthworth** [comment]
We have results <- list() which has length 0.

We have
if(simulate & match<length(results) & method!="exact.sim"){

which can be simplified to
if(match < length(results)){

for the example I posted.

So that gets evaluated only after we've done 100 iterations and results has been bound with subset.results. ndose gets reassigned inside that repeat{ codeblock.

**Comment by harrysouthworth** [comment]
Version 0.3 (from CRAN archives) contains the first version of the repeat{} codeblock and the NEWS file states:
* Simulations now run faster, as they use information from identical previous simulations to choose next dose. This is only implemented if nsims<=1000, otherwise the computation time to search previous simulations becomes unmanageable.

Although the tox results might be the same, does that imply that the next dose has to be the same. Won't the prior be different because at later iterations it's based on more data?

In any event, if it's just a speed thing, can't the whole construct just be removed so long as I'm patient enough to wait?

**Comment by mikesweeting** [comment]
Thanks Harry, certainly something odd going on here. Will try to get round
to having a look at this shortly.

Best wishes
Mike

**Comment by harrysouthworth** [comment]
Thanks. Ignore my question above about whether the next dose has to be the same if the tox results are the same. I think it does. So the issue must be in the matching. Anyway, I can work around by just doing the simulations and not the search.

Ta,
Harry
